
- template:
    src: "setup/{{item}}"
    dest: "{{quay_hostdir}}/{{item}}"
    trim_blocks: false
    force: true
  loop: [quay.yml]

- template:
    src: "setup/{{item}}"
    dest: "{{quay_hostdir}}/{{item}}"
    trim_blocks: false
    mode: "0750"
    force: true
  loop: [wrap_prepare]

- shell: "{{quay_hostdir}}/wrap_prepare"
