---
- name: Create directories
  file:
    path: "{{quay_versioned_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{quay_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{quay_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "item.path|regex_search('\\.frep$|conf.d')"
- shell: |-
     set -e
     SKIP_PREPARE=1 {{quay_hostdir}}/wrap_prepare
  changed_when: false
  tags: [gen_prepare]
- name: Synchronise scripts
  delegate_to: "localhost"
  synchronize:
    compress: false
    ssh_args: "{{quay_sshargs}}"
    src: "./scripts/"
    dest: "{{quay_hostdir}}/scripts/"
    rsync_opts: "{{quay_code_rsync_opts}}"
    set_remote_user: "no"
  tags: [sync_scripts]
- block:
  - shell: "{{quay_hostdir}}/fix.sh"
    name: "fix setup (perms & confs)"
    tags: [fix]
